### ISSUE TITLE
ADC: libcublas.so.9.0 issue

### ISSUE THREAD

**Issue by HKLee2040** [NervanaSystems/distiller#111]
I follow the steps:
After creating the virtual environment and installing Distiller's Python package dependencies, go ahead and setup Coach per: https://github.com/NervanaSystems/coach#installation.

%%%  in this step, tensorflow-gpu 1.12.0 is installed automatically

Make sure that you install Coach's package dependencies into the same virtual environment that already contains Distiller's dependency packages.  You do this by ensuring that Distiller's virtual environment is the active environment when you install Coach.
*NOTE: you may need to update TensorFlow to the expected version:
    $ pip3 install tensorflow==1.9.0

%%% Actually, I re-install tensorflow-gpu==1.9.0 at final step

However, I met the following trouble, libcublas.so.9.0 is needed!

Traceback (most recent call last):
  File "/media/walker/DATA/work/new_quant/distiller/coach_env/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/media/walker/DATA/work/new_quant/distiller/coach_env/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/media/walker/DATA/work/new_quant/distiller/coach_env/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/media/walker/DATA/work/new_quant/distiller/coach_env/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/media/walker/DATA/work/new_quant/distiller/coach_env/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

Would you tell me which step is wrong?

**Comment by nzmora** [comment]
HI @HKLee2040 

Maybe this is because you upgraded ```tensorflow-gpu``` instead of ```tensorflow```?
Can you try 
```
$ pip3 install tensorflow==1.9.0
```

This is my machine - I'm still using ibcublas.so.8.0, not ibcublas.so.9.0:

```
$ find /usr/local/cuda-8.0/ -name "libcublas.so*"
/usr/local/cuda-8.0/targets/x86_64-linux/lib/stubs/libcublas.so
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcublas.so.8.0.61
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcublas.so.8.0
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcublas.so
/usr/local/cuda-8.0/doc/man/man7/libcublas.so.7
```

Cheers,
Neta

**Comment by HKLee2040** [comment]
@nzmora 
Thanks, after installing tensorflow (cpu), the problem is solved.
However, I met another trouble, would you help me, please?

Creating graph - name: BasicRLGraphManager

--------------------------------------------------------
Logging to TensorBoard - remember to execute the server:
> tensorboard --logdir='./logs'

Failed to instantiate Gym environment class <class 'module.CNNEnvironment'> with arguments {'model': DataParallel(
  (module): PlainCifar(
    (conv1): Conv2d(3, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (bn1): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU(inplace)
    (layer1): Sequential(
      (0): BasicBlock(
        (conv1): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU()
        (conv2): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU()
      )
      (1): BasicBlock(
        (conv1): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU()
        (conv2): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU()
      )
      (2): BasicBlock(
        (conv1): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU()
        (conv2): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU()
      )
    )
    (layer2): Sequential(
      (0): BasicBlock(
        (conv1): Conv2d(16, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU()
        (conv2): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU()
      )
      (1): BasicBlock(
        (conv1): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU()
        (conv2): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU()
      )
      (2): BasicBlock(
        (conv1): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU()
        (conv2): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU()
      )
    )
    (layer3): Sequential(
      (0): BasicBlock(
        (conv1): Conv2d(32, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU()
        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU()
      )
      (1): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU()
        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU()
      )
      (2): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU()
        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU()
      )
    )
    (avgpool): AvgPool2d(kernel_size=8, stride=1, padding=0)
    (fc): Linear(in_features=64, out_features=10, bias=True)
  )
), 'services': {'validate_fn': functools.partial(<function validate at 0x7f5ebed7f378>, criterion=CrossEntropyLoss(), args=Namespace(ADC=True, ADC_params=None, activation_stats=None, arch='plain20_cifar', batch_size=256, compress=None, data='../../../data.cifar10', dataset='cifar10', deterministic=False, display_confusion=True, earlyexit_lossweights=None, earlyexit_thresholds=None, epochs=90, evaluate=False, extras=None, gpus=None, kd_distill_wt=0.5, kd_pretrained=False, kd_resume='', kd_start_epoch=0, kd_student_wt=0.5, kd_teacher=None, kd_teacher_wt=0.0, kd_temp=1.0, load_serialized=False, log_params_histograms=False, lr=0.1, masks_sparsity=False, momentum=0.9, name='AMC-plain20', num_best_scores=1, num_classes=10, output_dir='logs', pretrained=False, print_freq=10, qe_bits_accum=32, qe_bits_acts=8, qe_bits_wts=8, qe_clip_acts=False, qe_mode=<LinearQuantMode.SYMMETRIC: 1>, qe_no_clip_layers=[], qe_per_channel=False, quantize_eval=False, resume='../cifar10/teacher_resnet/plain20_checkpoint.pth.tar', sensitivity=None, sensitivity_range=[0.0, 0.95, 0.05], summary=None, validation_size=0.1, weight_decay=0.0001, workers=4), loggers=[<distiller.data_loggers.logger.PythonLogger object at 0x7f5ebedaf6a0>], val_loader=<torch.utils.data.dataloader.DataLoader object at 0x7f5e476c46a0>), 'save_checkpoint_fn': functools.partial(<function save_checkpoint at 0x7f5ed871b6a8>, dir='logs/AMC-plain20___2018.12.21-081021', arch='plain20_cifar'), 'train_fn': functools.partial(<function train at 0x7f5ebed7f2f0>, criterion=CrossEntropyLoss(), args=Namespace(ADC=True, ADC_params=None, activation_stats=None, arch='plain20_cifar', batch_size=256, compress=None, data='../../../data.cifar10', dataset='cifar10', deterministic=False, display_confusion=True, earlyexit_lossweights=None, earlyexit_thresholds=None, epochs=90, evaluate=False, extras=None, gpus=None, kd_distill_wt=0.5, kd_pretrained=False, kd_resume='', kd_start_epoch=0, kd_student_wt=0.5, kd_teacher=None, kd_teacher_wt=0.0, kd_temp=1.0, load_serialized=False, log_params_histograms=False, lr=0.1, masks_sparsity=False, momentum=0.9, name='AMC-plain20', num_best_scores=1, num_classes=10, output_dir='logs', pretrained=False, print_freq=10, qe_bits_accum=32, qe_bits_acts=8, qe_bits_wts=8, qe_clip_acts=False, qe_mode=<LinearQuantMode.SYMMETRIC: 1>, qe_no_clip_layers=[], qe_per_channel=False, quantize_eval=False, resume='../cifar10/teacher_resnet/plain20_checkpoint.pth.tar', sensitivity=None, sensitivity_range=[0.0, 0.95, 0.05], summary=None, validation_size=0.1, weight_decay=0.0001, workers=4), loggers=[<distiller.data_loggers.logger.PythonLogger object at 0x7f5ebedaf6a0>], train_loader=<torch.utils.data.dataloader.DataLoader object at 0x7f5e476c4518>)}, 'amc_cfg': {'conv_cnt': 19, 'max_reward': -1000, 'action_range': (0.2, 0.8), 'desired_reduction': None, 'reward_fn': <function coach_adc.<locals>.<lambda> at 0x7f5f13d53158>, 'normalize_obs': True, 'onehot_encoding': False}, 'app_args': {'optimizer_data': {'lr': 0.1, 'momentum': 0.9, 'weight_decay': 0.0001}, 'dataset': 'cifar10', 'arch': 'plain20_cifar'}}

Log file for this run: /media/walker/DATA/work/new_quant/distiller/examples/classifier_compression/logs/AMC-plain20___2018.12.21-081021/AMC-plain20___2018.12.21-081021.log
Traceback (most recent call last):
  File "compress_classifier.py", line 816, in <module>
    main()
  File "compress_classifier.py", line 346, in main
    return automated_deep_compression(model, criterion, optimizer, pylogger, args)
  File "compress_classifier.py", line 811, in automated_deep_compression
    ADC.do_adc(model, args.dataset, args.arch, optimizer_data, validate_fn, save_checkpoint_fn, train_fn)
  File "/media/walker/DATA/work/new_quant/distiller/examples/automated_deep_compression/ADC.py", line 80, in do_adc
    return coach_adc(model, dataset, arch, optimizer_data, validate_fn, save_checkpoint_fn, train_fn)
  File "/media/walker/DATA/work/new_quant/distiller/examples/automated_deep_compression/ADC.py", line 136, in coach_adc
    graph_manager.create_graph(task_parameters)
  File "/media/walker/DATA/work/new_quant/distiller/env/lib/python3.5/site-packages/rl_coach/graph_managers/graph_manager.py", line 144, in create_graph
    self.level_managers, self.environments = self._create_graph(task_parameters)
  File "/media/walker/DATA/work/new_quant/distiller/env/lib/python3.5/site-packages/rl_coach/graph_managers/basic_rl_graph_manager.py", line 51, in _create_graph
    visualization_parameters=self.visualization_parameters)
  File "/media/walker/DATA/work/new_quant/distiller/env/lib/python3.5/site-packages/rl_coach/environments/gym_environment.py", line 279, in __init__
    self.env = env_class(**self.additional_simulator_parameters)
  File "../automated_deep_compression/ADC.py", line 150, in __init__
    self.conv_layers, self.dense_model_macs, self.dense_model_size = collect_conv_details(model, self.app_args.dataset)
  File "../automated_deep_compression/ADC.py", line 523, in collect_conv_details
    assert conv_op is not None
AssertionError

**Comment by HKLee2040** [comment]
@nzmora 
I had pulling the latest code.
git clone https://github.com/NervanaSystems/distiller.git

The error message is the same.

**Comment by HKLee2040** [comment]
The problem might be here:
conv_op = g.find_op(normalize_module_name(name))
conv_op is "None"

where
name --> module.conv1
normalize_module_name(name) --> conv1
model.cuda() -->
DataParallel(
  (module): PlainCifar(
    (conv1): Conv2d(3, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (bn1): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU(inplace)
    (layer1): Sequential(
      (0): BasicBlock(
        (conv1): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU()
        (conv2): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU()
      )
      (1): BasicBlock(
        (conv1): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU()
        (conv2): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU()
      )
      (2): BasicBlock(
        (conv1): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU()
        (conv2): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU()
      )
    )
    (layer2): Sequential(
      (0): BasicBlock(
        (conv1): Conv2d(16, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU()
        (conv2): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU()
      )
      (1): BasicBlock(
        (conv1): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU()
        (conv2): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU()
      )
      (2): BasicBlock(
        (conv1): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU()
        (conv2): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU()
      )
    )
    (layer3): Sequential(
      (0): BasicBlock(
        (conv1): Conv2d(32, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU()
        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU()
      )
      (1): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU()
        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU()
      )
      (2): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU()
        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU()
      )
    )
    (avgpool): AvgPool2d(kernel_size=8, stride=1, padding=0)
    (fc): Linear(in_features=64, out_features=10, bias=True)
  )
and 
dummy_input.cuda() --> 
tensor([[[[-1.2363, -1.8887, -1.5269,  ...,  0.7919,  0.0512, -0.6660],
          [-1.4182, -0.2931,  1.3226,  ...,  0.2405,  0.0778,  2.0402],
          [ 1.2507,  0.4423, -0.4137,  ...,  0.1803,  1.0420,  1.0903],
          ...,
          [-0.7232,  0.4308,  0.3200,  ..., -0.7391, -0.2851, -0.4146],
          [ 1.2117, -0.0228, -0.0151,  ...,  0.6044,  0.9769,  0.8907],
          [-1.4293, -0.0233,  1.5798,  ...,  1.5356, -0.2819,  0.0576]],

         [[-0.2902, -0.4621,  1.1833,  ..., -0.2945, -0.7677,  0.9962],
          [ 0.9656, -0.1064,  0.7362,  ...,  0.0140, -1.5428,  1.5512],
          [ 1.7485, -1.0764, -1.0224,  ...,  0.9637,  0.9454, -0.9453],
          ...,
          [-0.5498, -0.5892, -2.2179,  ..., -0.3664,  1.0284, -0.4368],
          [-0.4722,  2.1218,  0.6156,  ..., -0.4631, -1.2541,  1.1191],
          [-1.4256, -1.2459,  0.8530,  ..., -1.2808,  0.1569,  1.8153]],

         [[ 0.0089,  0.5651, -0.4222,  ..., -1.4444, -1.6593,  1.9119],
          [-0.1775,  0.4711,  0.5916,  ..., -0.5752, -0.1570, -0.0151],
          [-1.4817,  0.3288, -0.9032,  ...,  0.0155, -1.6745, -0.9495],
          ...,
          [ 0.8388,  0.0050, -2.6391,  ..., -1.6780,  1.3266,  1.5418],
          [ 0.2394,  1.2393,  0.9745,  ...,  1.3917, -0.5422, -0.8599],
          [ 0.5559,  1.2866,  0.9453,  ...,  0.1012,  0.8200, -0.7340]]]], device='cuda:0')

**Comment by nzmora** [comment]
@HKLee2040 
Right - try removing ```normalize_module_name```.  I think it will work as a quick hack until we debug this further.  
This has to do with how DataParallel behaves on systems with a single GPU (I assume that this is your setup).  On our cluster we don't have such machines unfortunately.

Cheers
Neta

**Comment by HKLee2040** [comment]
@nzmora Yes, it works.  Thanks!
