### ISSUE TITLE
RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:383

### ISSUE THREAD

**Issue by georgetseng1128** [NervanaSystems/distiller#299]
I command  in the path: /distille/examples/classifier_compression is:
`python compress_classifier.py -a resnet18 /mnt/83a7cab6-2970-47cf-b4ae-9e770da2cb65/dataset/imagenet2012 --compress=../quantization/quant_aware_train/quant_aware_train_linear_quant.yaml`
return error:
RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:383

This is my information:

System is Ubuntu18.04 

GPU: RTX2080TI

Environment:
$ nvcc --version 
>> Cuda compilation tools, release 9.2, V9.2.148

$ import torch
$ print(torch.__version__)
>> 1.1.0

$nvidia-smi
>> NVIDIA-SMI 430.26       Driver Version: 430.26       CUDA Version: 10.2

And other CNN case GPU can be run.

Please help!

**Comment by hunterkun** [comment]
I encounter same questions, and solved by installing CUDA 10 instead 9. It seems related to the 2080ti gpu.

**Comment by nzmora** [comment]
Hi @georgetseng1128,
Following @hunterkun's advice, take a look at the solution to https://github.com/NervanaSystems/distiller/issues/267 - maybe this is related to your issue.
Cheers
Neta

**Comment by georgetseng1128** [comment]
Thank all, I can solve this issue by CUDA10.
