### ISSUE TITLE
RuntimeError: cuda runtime error (30) 

### ISSUE THREAD

**Issue by zhuhui123** [NervanaSystems/distiller#31]
An error occurred: 
RuntimeError: cuda runtime error (30) : unknown error at /pytorch/aten/src/THC/THCTensorRandom.cu:25
My env is ubuntu 18.04, cuda 8.0, torch-0.4.0, python 3.6. Which one is wrong？Or what's the reason?
In the document "readme" shows that:
PyTorch is included in the requirements.txt file, and will currently download PyTorch version 3.1 for CUDA 8.0. This is the setup we've used for testing Distiller.
But the requirements.txt shows that the torch version is 0.4.0.
What are the final versions? Which cuda and which torch and the others.

**Comment by guyjacob** [comment]
The PyTorch version currently required is 0.4.0. I'll update the README to reflect that (thanks for catching it).
Other than that, as stated in the readme we've tested Distiller on Ubuntu 16.04 + CUDA 8.0 + Python 3.5, and that's the only setup we can provide support for at the moment. So we won't be able to re-produce your error on our end.

The error you're getting is a generic CUDA error, so it's hard to say exactly what's happening here. Are you able to run PyTorch with GPU successfully without Distiller (for example, their ImageNet sample [here](https://github.com/pytorch/examples/tree/master/imagenet))? If that works, then please provide more details on the error you're getting with Distiller - where exactly does it occur - and we'll try to help.

**Comment by zhuhui123** [comment]
Thank you. I have solved this problem. It need root permission to read the GPU device number. "sudo" can solve it.
